<?php

$title = 'Deletar produto';
$this->headTitle($title);
?>
<h2><?= $this->escapeHtml($title) ?></h2>
<?php
/* @var $form \Produto\Form\ProdutoForm */
$form->setAttribute('action', $this->url('produto', ['action' => 'delete','id' => $id,]));
$form->prepare();

$idForm     = $form->get('id');
$nome       = $form->get('nome');
$nome->setAttribute('readonly', 'true');
$nome->setAttribute('disabled', 'true');

$categoria  = $form->get('categoria');
$categoria->setAttribute('readonly', 'true');
$categoria->setAttribute('disabled', 'true');

$unidade    = $form->get('unidade');
$unidade->setAttribute('readonly', 'true');
$unidade->setAttribute('disabled', 'true');

$descricao  = $form->get('descricao');
$descricao->setAttribute('readonly', 'true');
$descricao->setAttribute('disabled', 'true');

$submit     = $form->get('submit');
$submit->setAttribute('class', 'btn btn-sm btn-danger');

echo $this->form()->openTag($form);

?>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"><?= $nome->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formElement($nome) ?>
    </div>
    <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"><?= $categoria->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formElement($categoria) ?>
    </div>
    <?= $this->formElementErrors()->render($categoria, ['class' => 'help-block']) ?>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"><?= $unidade->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formElement($unidade) ?>
    </div>
    <?= $this->formElementErrors()->render($unidade, ['class' => 'help-block']) ?>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label"><?= $descricao->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formElement($descricao) ?>
    </div>
    <?= $this->formElementErrors()->render($descricao, ['class' => 'help-block']) ?>
</div>

<div class="btn-group-sm">

<?php
echo $this->formSubmit($submit);
?>
    <a href="<?= $this->url('produto', ['action' => 'index']) ?>" class="btn btn-sm btn-warning">Cancelar</a>

</div>

<?php
echo $this->form()->closeTag();