<?php

$title = 'Listagem de Produtos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn-sm btn-primary" href="<?= $this->url('produto', ['action' => 'add']) ?>">Incluir</a>
</p>

<div class="table-responsive table-responsive-sm">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th scope="col" style="width: 100px;">Código</th>
                <th scope="col">Nome</th>
                <th scope="col" style="width: 100px;">Unidade</th>
                <th scope="col" style="width: 150px;">Categoria</th>
                <th scope="col" style="width: 100px; text-align: right;">Qtde. Estoque</th>
                <th scope="col" style="width: 150px">&nbsp;</th>
            </tr>
        </thead>
    <?php foreach ($produtos as /* @var $produto Produto\Model\Produto */ $produto) : ?>
        <tr>
            <td><?= $this->escapeHtml($produto->id) ?></td>
            <td><?= $this->escapeHtml($produto->nome) ?></td>
            <td><?= $this->escapeHtml($produto->getDestricaoUnidade()) ?></td>
            <td><?= $this->escapeHtml($produto->getDestricaoCategoria()) ?></td>
            <td style="text-align: right" ><?= $this->escapeHtml(number_format(0, 2, ',', '.')) ?></td>
            <td style="text-align: right" >
                <a class="btn-sm btn-primary" href="<?= $this->url('produto', ['action' => 'edit', 'id' => $produto->id]) ?>">Alterar</a>
                <a class="btn-sm btn-danger" href="<?= $this->url('produto', ['action' => 'delete', 'id' => $produto->id]) ?>">Excluir</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>