<?php

$title = "Listagem de Itens da Entrada $idEntrada";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <?php if($entrada->situacao != Estoque\Model\Entrada::SITUACAO_CONCLUIDA) : ?>
    <a class="btn-sm btn-primary" href="<?= $this->url('item-entrada', ['action' => 'add', 'identrada' => $idEntrada]) ?>">Incluir</a>
    <?php endif; ?>

    <a class="btn-sm btn-primary" href="<?= $this->url('entrada') ?>">Voltar</a>
</p>

<div class="table-responsive table-responsive-sm">
    <table class="table table-sm table-striped">
        <thead>
            <th scope="col" style="width: 100px;">Item</th>
            <th scope="col">Nome</th>
            <th scope="col" style="width: 100px; text-align: right">Quantidade</th>
            <th scope="col" style="width: 100px; text-align: right">Vlr. Unitário</th>
            <th scope="col" style="width: 100px; text-align: right">Vlt. Total</th>
            <th scope="col" style="width: 100px; text-align: center">Ações</th>
        </thead>
    <?php foreach ($itensEntrada as /* @var $itemEntrada Estoque\Model\ItemEntrada */ $itemEntrada) : ?>
        <tr>
            <td><?= $this->escapeHtml($itemEntrada->id) ?></td>
            <td><?= $this->escapeHtml($itemEntrada->produto()->nome) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemEntrada->quantidade, 2, ',', '.')) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemEntrada->valorunitario, 2, ',', '.')) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemEntrada->valortotal, 2, ',', '.')) ?></td>

            <td style="text-align: right">
                <?php if($itemEntrada->entrada()->situacao != Estoque\Model\Entrada::SITUACAO_CONCLUIDA) : ?>

                <a  title="Alterar" class="btn-sm btn-primary" style="margin: 1px;"
                    href="<?= $this->url('item-entrada', ['action' => 'edit', 'identrada' => $itemEntrada->identrada, 'id' => $itemEntrada->id]) ?>">
                    <img src="/open-iconic/svg/pencil.svg" alt="Alterar">
                </a>

                <a  title="Excluir" class="btn-sm btn-danger" style="margin: 1px;"
                    href="<?= $this->url('item-entrada', ['action' => 'delete', 'identrada' => $itemEntrada->identrada, 'id' => $itemEntrada->id]) ?>">
                    <img src="/open-iconic/svg/trash.svg" alt="Excluir">
                </a>

                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>