<?php

$title = 'Listagem de Entradas';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn-sm btn-primary" href="<?= $this->url('entrada', ['action' => 'add']) ?>">Incluir</a>
</p>

<div class="table-responsive-sm">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th scope="col" style="width: 80px;">Código</th>
                <th scope="col" style="width: 100px;">Data</th>
                <th scope="col" style="width: 100px;">Hora</th>
                <th scope="col" style="width: 100px;">Nº Nota Fiscal</th>
                <th scope="col">Fornecedor</th>
                <th scope="col" style="width: 150px;">Situação</th>
                <th scope="col" style="width: 100px;text-align: right">Valor Total</th>
                <th scope="col" style="width: 50px;text-align: right">Ações</th>
            </tr>
        </thead>
    <?php foreach ($entradas as /* @var $entrada Estoque\Model\Entrada */ $entrada) : ?>
        <tr>
            <td><?= $this->escapeHtml($entrada->id) ?></td>
            <td><?= $this->escapeHtml(date_format(date_create($entrada->data), 'd/m/Y')) ?></td>
            <td><?= $this->escapeHtml($entrada->hora) ?></td>
            <td><?= $this->escapeHtml($entrada->numero_nota) ?></td>
            <td><?= $this->escapeHtml($entrada->fornecedor()->pessoa()->nome) ?></td>
            <td><?= $this->escapeHtml($entrada->getDestricaoSituacao()) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format(0, 2, ',', '.')) ?></td>
            <td style="text-align: right">
                <div class="btn-group btn-group-vertical btn-group-sm" role="group">
                    <button id="btnGroupAcoes" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupAcoes" style="padding: 0px; min-width:60px;">
                        <a class="btn-sm btn-primary" style="margin: 2px" href="<?= $this->url('entrada', ['action' => 'edit', 'id' => $entrada->id]) ?>">Alterar</a>
                        <a class="btn-sm btn-danger" style="margin: 2px" href="<?= $this->url('entrada', ['action' => 'delete', 'id' => $entrada->id]) ?>">Excluir</a>
                    </div>
                </div>

            </td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>