<?php

$title = 'Listagem de Entradas';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a title="Incluir" class="btn-sm btn-primary" href="<?= $this->url('entrada', ['action' => 'add']) ?>">
        <img src="/open-iconic/svg/plus.svg" alt="Incluir">
    </a>
</p>

<div class="table-responsive table-responsive-sm">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th scope="col" style="width: 80px;">Código</th>
                <th scope="col" style="width: 100px;">Data</th>
                <th scope="col" style="width: 100px;">Hora</th>
                <th scope="col" style="width: 100px;">Nº Nota Fiscal</th>
                <th scope="col">Fornecedor</th>
                <th scope="col" style="width: 150px;">Situação</th>
                <th scope="col" style="width: 100px;text-align: right">Valor Total</th>
                <th scope="col" style="width: 160px;text-align: center">Ações</th>
            </tr>
        </thead>
    <?php foreach ($entradas as /* @var $entrada Estoque\Model\Entrada */ $entrada) : ?>
        <tr>
            <td><?= $this->escapeHtml($entrada->id) ?></td>
            <td><?= $this->escapeHtml(date_format(date_create($entrada->data), 'd/m/Y')) ?></td>
            <td><?= $this->escapeHtml($entrada->hora) ?></td>
            <td><?= $this->escapeHtml($entrada->numero_nota) ?></td>
            <td><?= $this->escapeHtml($entrada->fornecedor()->pessoa()->nome) ?></td>
            <td><?= $this->escapeHtml($entrada->getDestricaoSituacao()) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($entrada->getValorTotal(), 2, ',', '.')) ?></td>
            <td style="text-align: right">
                <a  title="Alterar" class="btn-sm btn-primary" style="margin: 1px;"
                    href="<?= $this->url('entrada', ['action' => 'edit', 'id' => $entrada->id]) ?>">
                    <img src="/open-iconic/svg/pencil.svg" alt="Alterar">
                </a>
                <a  title="Excluir" class="btn-sm btn-danger" style="margin: 1px;"
                    href="<?= $this->url('entrada', ['action' => 'delete', 'id' => $entrada->id]) ?>">
                    <img src="/open-iconic/svg/trash.svg" alt="Excluir">
                </a>
                <a  title="Itens" class="btn-sm btn-primary" style="margin: 1px;"
                    href="<?= $this->url('item-entrada', ['action' => 'index', 'identrada' => $entrada->id]) ?>">
                    <img src="/open-iconic/svg/cart.svg" alt="Itens">
                </a>
                <a  title="Concluir" class="btn-sm btn-primary" style="margin: 1px;"
                    href="<?= $this->url('entrada', ['action' => 'conclui', 'id' => $entrada->id]) ?>">
                    <img src="/open-iconic/svg/check.svg" alt="Concluir">
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>

</div>

<?php

/* @var $entradas \Zend\Paginator\Paginator */
$dataPage = $entradas->getPages();

?>

<nav aria-label="Paginação">
  <ul class="pagination">

    <?php if (isset($dataPage->previous)) : ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url('entrada-page', ['page' => $dataPage->previous]) ?>">Anterior</a></li>
    <?php endif; ?>

    <?php if (!isset($dataPage->pagesInRange[1])) : ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url('entrada-page', ['page' => 1]) ?>">1</a></li>
        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">---</a></li>
    <?php endif; ?>

    <?php foreach ($dataPage->pagesInRange as $page) : ?>
        <?php if ($dataPage->current != $page) : ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url('entrada-page', ['page' => $page]) ?>"><?= $page ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (!isset($dataPage->pagesInRange[$dataPage->pageCount])) : ?>
        <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">---</a></li>
        <li class="page-item"><a class="page-link" href="<?= $this->url('entrada-page', ['page' => $dataPage->pageCount]) ?>"><?= $dataPage->pageCount ?></a></li>
    <?php endif; ?>

    <?php if (isset($dataPage->next)) : ?>
        <li class="page-item"><a class="page-link" href="<?= $this->url('entrada-page', ['page' => $dataPage->next]) ?>">Próximo</a></li>
    <?php endif; ?>

  </ul>
</nav>