<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Direção do Estoque')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Direção do Estoque
                    </a>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <?php if(Auth\Model\Auth::check()) {?>
                        <li class="nav-item dropdown">
                            <a id="navbarCadastro" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cadastros<span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarCadastro">
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('pessoa') ?>">Pessoa</a>
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('fornecedor') ?>">Fornecedor</a>
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('produto') ?>">Produto</a>
                            </div>

                        </li>

                        <li class="nav-item dropdown">
                            <a id="navbarGerenciar" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Gerenciar<span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarGerenciar">
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('entrada') ?>">Entradas</a>
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('saida') ?>">Saídas</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarConsultar" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Consultas<span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarConsultar">
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('movimentacoes-estoque') ?>">Movimentações</a>
                            </div>
                        </li>
                        <?php } ?>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <?php if(!Auth\Model\Auth::check()) { ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('auth') ?>">Login</a>
                            </li>
                        <?php } ?>

                        <?php if(Auth\Model\Auth::check()) { ?>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?= Auth\Model\Auth::identity() ?><span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item btn btn-sm btn-light" href="<?= $this->url('logout') ?>">Sair</a>
                            </div>
                        </li>
                        <?php } ?>
                    </ul>
                </div>

            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
