<?php

$title = "Listagem de Itens da Saida $idSaida";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <?php if($saida->situacao != Estoque\Model\Saida::SITUACAO_CONCLUIDA) : ?>
    <a class="btn-sm btn-primary" href="<?= $this->url('item-saida', ['action' => 'add', 'idsaida' => $idSaida]) ?>">Incluir</a>
    <?php endif; ?>

    <a class="btn-sm btn-primary" href="<?= $this->url('saida') ?>">Voltar</a>
</p>

<div class="table-responsive table-responsive-sm">
    <table class="table table-sm table-striped">
        <thead>
            <th scope="col" style="width: 100px;">Item</th>
            <th scope="col">Nome</th>
            <th scope="col" style="width: 100px; text-align: right">Quantidade</th>
            <th scope="col" style="width: 100px; text-align: right">Vlr. Unitário</th>
            <th scope="col" style="width: 100px; text-align: right">Vlt. Total</th>
            <th scope="col" style="width: 50px;">Ações</th>
        </thead>
    <?php foreach ($itensSaida as /* @var $itemSaida Estoque\Model\ItemSaida */ $itemSaida) : ?>
        <tr>
            <td><?= $this->escapeHtml($itemSaida->id) ?></td>
            <td><?= $this->escapeHtml($itemSaida->produto()->nome) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemSaida->quantidade, 2, ',', '.')) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemSaida->valorunitario, 2, ',', '.')) ?></td>
            <td style="text-align: right"><?= $this->escapeHtml(number_format($itemSaida->valortotal, 2, ',', '.')) ?></td>

            <td style="text-align: right">
                <?php if($itemSaida->saida()->situacao != Estoque\Model\Saida::SITUACAO_CONCLUIDA) : ?>

                <div class="btn-group btn-group-vertical btn-group-sm" role="group">
                    <button id="btnGroupAcoes" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupAcoes" style="padding: 0px; min-width:60px;">
                        <a class="btn-sm btn-primary" style="margin: 2px;" href="<?= $this->url('item-saida', ['action' => 'edit', 'idsaida' => $itemSaida->idsaida, 'id' => $itemSaida->id]) ?>">Alterar</a>
                        <a class="btn-sm btn-danger" style="margin: 2px;" href="<?= $this->url('item-saida', ['action' => 'delete', 'idsaida' => $itemSaida->idsaida, 'id' => $itemSaida->id]) ?>">Excluir</a>
                    </div>
                </div>

                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>