<?php

/* @var $form \Pessoa\Form\PessoaForm */
$form->setAttribute('action', $this->url('auth', ['action' => 'login']));
$form->setAttribute('class' , 'form-signin');
$form->prepare();

$email    = $form->get('email');
$password = $form->get('password');
$remember = $form->get('rememberme');
$submit   = $form->get('submit');

?>

<?php if(isset($errors) && count($errors) > 0) { ?>

<div class="alert alert-danger">
    <ul>
        <?php foreach($errors as $error) { ?>

        <li><?= $error ?></li>

        <?php } ?>
    </ul>
</div>

<?php } ?>

<div class="container">
    <div class="row" style="justify-content: center!important; display:flex; flex-wrap:wrap;">
        <div class="col-md-4">
            <?= $this->form()->openTag($form) ?>
                <h3 class="h3 mb-3 font-weight-normal">Por favor, faça login</h3>

                <label for="inputEmail" class="sr-only">Endereço de Email</label>
                <?= $this->formElement($email) ?>
                <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>

                <label for="inputPassword" class="sr-only">Password</label>
                <?= $this->formElement($password) ?>
                <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>

                <div class="checkbox mb-3">
                    <label>
                        <?= $this->formElement($remember) ?>
                        Lembre de Min
                    </label>
                </div>

                <?= $this->formSubmit($submit) ?>

            <?= $this->form()->closeTag() ?>

        </div>
    </div>
</div>