<div class="container">
    <div class="row" style="justify-content: center!important; display:flex; flex-wrap:wrap;">
        <div class="col-md-4">
            <form class="form-signin">
                <h3 class="h3 mb-3 font-weight-normal">Por favor, faça login</h3>
                <label for="inputEmail" class="sr-only">Endereço de Email</label>
                <input type="email" id="inputEmail" class="form-control" placeholder="Endereço de Email" required autofocus>
                <label for="inputPassword" class="sr-only">Password</label>
                <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required>
                <div class="checkbox mb-3">
                    <label>
                        <input type="checkbox" value="remember-me">Lembre de min
                    </label>
                </div>
                <button class="btn btn-sm btn-primary btn-block" type="submit">Confirmar</button>
            </form>
        </div>
    </div>
</div>