<div class="jumbotron">
    <h1>Bem vindo ao <span class="zf-green">Zend Framework</span></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Informações</h3>
            </div>
            <div class="panel-body">
                <p>
                    Você está logado
                </p>
            </div>
        </div>
    </div>

</div>
